// All available icons for the portfolio website
// These icons are from lucide-react and react-icons
// Admin panel will allow selecting from these icons

import {
  Home,
  User,
  Briefcase,
  GraduationCap,
  Wrench,
  Award,
  Mail,
  Phone,
  MapPin,
  Calendar,
  ExternalLink,
  Github,
  Linkedin,
  Facebook,
  Twitter,
  Instagram,
  Youtube,
  Globe,
  Code,
  Code2,
  Brain,
  Target,
  Eye,
  Heart,
  Star,
  Sparkles,
  Zap,
  TrendingUp,
  BarChart3,
  PieChart,
  Activity,
  Layers,
  Box,
  Boxes,
  Package,
  FolderOpen,
  FileText,
  File,
  Image,
  Video,
  Music,
  Camera,
  Gamepad2,
  Plane,
  BookOpen,
  Coffee,
  Download,
  Upload,
  Send,
  MessageCircle,
  MessageSquare,
  Bell,
  Settings,
  Search,
  Filter,
  Plus,
  Minus,
  X,
  Check,
  CheckCircle,
  CheckCircle2,
  AlertCircle,
  Info,
  HelpCircle,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Menu,
  MoreHorizontal,
  MoreVertical,
  Grid,
  List,
  LayoutGrid,
  LayoutList,
  Table,
  Palette,
  Paintbrush,
  Pencil,
  Edit,
  Trash,
  Trash2,
  Copy,
  Clipboard,
  Link,
  Unlink,
  Lock,
  Unlock,
  Key,
  Shield,
  ShieldCheck,
  UserCheck,
  Users,
  UserPlus,
  Building,
  Building2,
  Map,
  MapPinned,
  Navigation,
  Compass,
  Mountain,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Thermometer,
  Wind,
  Waves,
  TreePine,
  Leaf,
  Flower,
  Bug,
  Cpu,
  Database,
  Server,
  HardDrive,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Keyboard,
  Mouse,
  Printer,
  Wifi,
  Bluetooth,
  Battery,
  Power,
  Plug,
  Lightbulb,
  Rocket,
  Atom,
  Microscope,
  TestTube,
  Beaker,
  FlaskConical,
  Dna,
  HeartPulse,
  Stethoscope,
  Pill,
  Syringe,
  Ambulance,
  Hospital,
  Cross,
  Banknote,
  Coins,
  CreditCard,
  Wallet,
  PiggyBank,
  Receipt,
  Calculator,
  Percent,
  TrendingDown,
  DollarSign,
  Euro,
  PoundSterling,
  Bitcoin,
  Gem,
  Crown,
  Trophy,
  Medal,
  BadgeCheck,
  Ribbon,
  Gift,
  PartyPopper,
  Cake,
  Wine,
  Beer,
  Pizza,
  Apple,
  Carrot,
  Utensils,
  ChefHat,
  Store,
  ShoppingCart,
  ShoppingBag,
  Tag,
  Tags,
  Ticket,
  QrCode,
  Barcode,
  Scan,
  Fingerprint,
  Eye as EyeIcon,
  EyeOff,
  Ear,
  Hand,
  HandMetal,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Meh,
  Frown,
  Angry,
  Laugh,
  Ghost,
  Skull,
  Bot,
  Cat,
  Dog,
  Bird,
  Fish,
  Rabbit,
  Squirrel,
  type LucideIcon,
} from "lucide-react";

// Icon registry - all available icons
export const iconRegistry: Record<string, LucideIcon> = {
  // Navigation & UI
  home: Home,
  user: User,
  briefcase: Briefcase,
  "graduation-cap": GraduationCap,
  wrench: Wrench,
  award: Award,
  mail: Mail,
  phone: Phone,
  "map-pin": MapPin,
  calendar: Calendar,
  "external-link": ExternalLink,
  menu: Menu,
  search: Search,
  filter: Filter,
  settings: Settings,
  
  // Social
  github: Github,
  linkedin: Linkedin,
  facebook: Facebook,
  twitter: Twitter,
  instagram: Instagram,
  youtube: Youtube,
  globe: Globe,
  
  // Development
  code: Code,
  code2: Code2,
  brain: Brain,
  target: Target,
  cpu: Cpu,
  database: Database,
  server: Server,
  "hard-drive": HardDrive,
  
  // Actions
  eye: Eye,
  "eye-off": EyeOff,
  heart: Heart,
  star: Star,
  sparkles: Sparkles,
  zap: Zap,
  download: Download,
  upload: Upload,
  send: Send,
  plus: Plus,
  minus: Minus,
  x: X,
  check: Check,
  "check-circle": CheckCircle,
  "check-circle2": CheckCircle2,
  edit: Edit,
  pencil: Pencil,
  trash: Trash,
  trash2: Trash2,
  copy: Copy,
  link: Link,
  
  // Charts & Data
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "bar-chart": BarChart3,
  "pie-chart": PieChart,
  activity: Activity,
  
  // Layout
  layers: Layers,
  box: Box,
  boxes: Boxes,
  package: Package,
  "folder-open": FolderOpen,
  grid: Grid,
  list: List,
  "layout-grid": LayoutGrid,
  table: Table,
  
  // Files & Media
  "file-text": FileText,
  file: File,
  image: Image,
  video: Video,
  music: Music,
  camera: Camera,
  
  // Lifestyle
  gamepad: Gamepad2,
  plane: Plane,
  "book-open": BookOpen,
  coffee: Coffee,
  palette: Palette,
  paintbrush: Paintbrush,
  
  // Messages
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  bell: Bell,
  
  // Arrows
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  
  // Security
  lock: Lock,
  unlock: Unlock,
  key: Key,
  shield: Shield,
  "shield-check": ShieldCheck,
  
  // Users
  "user-check": UserCheck,
  users: Users,
  "user-plus": UserPlus,
  
  // Location & Maps
  building: Building,
  building2: Building2,
  map: Map,
  "map-pinned": MapPinned,
  navigation: Navigation,
  compass: Compass,
  mountain: Mountain,
  
  // Weather & Nature
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  "cloud-rain": CloudRain,
  thermometer: Thermometer,
  wind: Wind,
  waves: Waves,
  "tree-pine": TreePine,
  leaf: Leaf,
  flower: Flower,
  
  // Devices
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  keyboard: Keyboard,
  printer: Printer,
  wifi: Wifi,
  
  // Science
  rocket: Rocket,
  atom: Atom,
  microscope: Microscope,
  "test-tube": TestTube,
  beaker: Beaker,
  flask: FlaskConical,
  dna: Dna,
  
  // Health
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  ambulance: Ambulance,
  hospital: Hospital,
  
  // Finance
  banknote: Banknote,
  coins: Coins,
  "credit-card": CreditCard,
  wallet: Wallet,
  "piggy-bank": PiggyBank,
  receipt: Receipt,
  calculator: Calculator,
  "dollar-sign": DollarSign,
  
  // Achievement
  trophy: Trophy,
  medal: Medal,
  "badge-check": BadgeCheck,
  ribbon: Ribbon,
  gift: Gift,
  crown: Crown,
  gem: Gem,
  
  // Food & Drink
  pizza: Pizza,
  apple: Apple,
  utensils: Utensils,
  "chef-hat": ChefHat,
  wine: Wine,
  beer: Beer,
  cake: Cake,
  
  // Shopping
  store: Store,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  tag: Tag,
  tags: Tags,
  ticket: Ticket,
  
  // Tech
  "qr-code": QrCode,
  barcode: Barcode,
  scan: Scan,
  fingerprint: Fingerprint,
  lightbulb: Lightbulb,
  power: Power,
  plug: Plug,
  battery: Battery,
  
  // Expressions
  smile: Smile,
  meh: Meh,
  frown: Frown,
  laugh: Laugh,
  "thumbs-up": ThumbsUp,
  "thumbs-down": ThumbsDown,
  
  // Animals & Characters
  bot: Bot,
  ghost: Ghost,
  cat: Cat,
  dog: Dog,
  bird: Bird,
  fish: Fish,
  rabbit: Rabbit,
  
  // Misc
  bug: Bug,
  info: Info,
  "help-circle": HelpCircle,
  "alert-circle": AlertCircle,
  "more-horizontal": MoreHorizontal,
  "more-vertical": MoreVertical,
  clipboard: Clipboard,
  "party-popper": PartyPopper,
};

// Get all icon names grouped by category
export const iconCategories = {
  "Navigation & UI": ["home", "user", "briefcase", "graduation-cap", "wrench", "award", "mail", "phone", "map-pin", "calendar", "external-link", "menu", "search", "filter", "settings"],
  "Social": ["github", "linkedin", "facebook", "twitter", "instagram", "youtube", "globe"],
  "Development": ["code", "code2", "brain", "target", "cpu", "database", "server", "hard-drive"],
  "Actions": ["eye", "heart", "star", "sparkles", "zap", "download", "upload", "send", "plus", "minus", "x", "check", "check-circle", "edit", "pencil", "trash", "copy", "link"],
  "Charts & Data": ["trending-up", "trending-down", "bar-chart", "pie-chart", "activity"],
  "Layout": ["layers", "box", "boxes", "package", "folder-open", "grid", "list", "layout-grid", "table"],
  "Files & Media": ["file-text", "file", "image", "video", "music", "camera"],
  "Lifestyle": ["gamepad", "plane", "book-open", "coffee", "palette", "paintbrush"],
  "Location & Maps": ["building", "building2", "map", "map-pinned", "navigation", "compass", "mountain"],
  "Weather & Nature": ["sun", "moon", "cloud", "thermometer", "wind", "waves", "tree-pine", "leaf", "flower"],
  "Devices": ["monitor", "smartphone", "tablet", "laptop", "keyboard", "printer", "wifi"],
  "Science": ["rocket", "atom", "microscope", "test-tube", "beaker", "flask", "dna"],
  "Finance": ["banknote", "coins", "credit-card", "wallet", "calculator", "dollar-sign"],
  "Achievement": ["trophy", "medal", "badge-check", "ribbon", "gift", "crown", "gem"],
  "Expressions": ["smile", "meh", "frown", "laugh", "thumbs-up", "thumbs-down"],
};

// Get icon component by name
export function getIcon(name: string): LucideIcon | null {
  return iconRegistry[name] || null;
}

// Get all icon names
export function getAllIconNames(): string[] {
  return Object.keys(iconRegistry);
}

export type IconName = keyof typeof iconRegistry;
